const APP_READ_LOCATION_REQUEST = "APP_READ_LOCATION_REQUEST";
const APP_READ_LOCATION_SUCCESS = "APP_READ_LOCATION_SUCCESS";
const APP_READ_LOCATION_FAILURE = "APP_READ_LOCATION_FAILURE";

export {
  APP_READ_LOCATION_REQUEST,
  APP_READ_LOCATION_SUCCESS,
  APP_READ_LOCATION_FAILURE,
};
